# config.py
# NON CARICARE QUESTO FILE SU REPOSITORY PUBBLICHE!
# Sostituisci "YOUR_GOOGLE_GEMINI_API_KEY" e "YOUR_OPENAI_API_KEY" con le tue chiavi reali.

GOOGLE_GEMINI_API_KEY = "YOUR_GOOGLE_GEMINI_API_KEY"
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"
